olist:
  target: dev
  outputs:
    dev:
      type: databricks
      catalog: "{{ env_var('DBT_CATALOG', 'olist_project_dev') }}"
      schema: olist_gold
      host: "{{ env_var('DBT_HOST', 'dbc-73e4c67b-b212.cloud.databricks.com') }}"
      http_path: "{{ env_var('DBT_HTTP_PATH') }}"
      token: "{{ env_var('DBT_TOKEN') }}"
      threads: 4

    prod:
      type: databricks
      catalog: "{{ env_var('DBT_CATALOG', 'olist_project_prod') }}"
      schema: olist_gold
      host: "{{ env_var('DBT_HOST', 'dbc-73e4c67b-b212.cloud.databricks.com') }}"
      http_path: "{{ env_var('DBT_HTTP_PATH') }}"
      token: "{{ env_var('DBT_TOKEN') }}"
      threads: 4
